angle_resolution: 0.087
angle_to_goal_th: 3.14
footprint_padding: 0.02
goal_threshold: 0.1
hz: 20.0
max_acceleration: 2.0
max_deceleration: 4.0
max_d_yawrate: 3.5
max_in_place_yawrate: 0.8
max_velocity: 3.0
max_yawrate: 3.0
min_in_place_yawrate: 0.3
min_velocity: 0.0
min_yawrate: 0.05
obs_cost_gain: 1.0
obs_range: 3.5
path_cost_gain: 0.4
predict_time: 2.0
robot_frame: 'base_link'
robot_radius: 0.18
sim_direction: 1.57
sim_period: 0.05
sim_time_samples: 15
sleep_time_after_finish: 0.5
slow_velocity_th: 0.1
speed_cost_gain: 0.4
subscribe_count_th: 3
target_velocity: 2.5
to_goal_cost_gain: 0.8
turn_direction_th: 0.1
use_footprint: false
use_path_cost: false
use_scan_as_input: true
velocity_samples: 8
v_path_width: 0.05
yawrate_samples: 20
