ANGLE_RESOLUTION: 0.087
ANGLE_TO_GOAL_TH: 3.141592653589793
FOOTPRINT_PADDING: 0.01
GLOBAL_FRAME: 'map'
GOAL_THRESHOLD: 0.1
HZ: 20
MAX_ACCELERATION: 0.5
MAX_DECELERATION: 2.0
MAX_D_YAWRATE: 3.2
MAX_IN_PLACE_YAWRATE: 0.6
MAX_VELOCITY: 1.0
MAX_YAWRATE: 1.0
MIN_IN_PLACE_YAWRATE: 0.3
MIN_VELOCITY: 0.0
MIN_YAWRATE: 0.05
OBSTACLE_COST_GAIN: 1.0
OBS_RANGE: 2.5
PATH_COST_GAIN: 0.4
PREDICT_TIME: 3.0
ROBOT_FRAME: 'base_link'
ROBOT_RADIUS: 0.1
SIM_DIRECTION: 1.5707963267948966
SIM_PERIOD: 0.1
SIM_TIME_SAMPLES: 10
SLEEP_TIME_AFTER_FINISH: 0.5
SLOW_VELOCITY_TH: 0.1
SPEED_COST_GAIN: 0.4
SUBSCRIBE_COUNT_TH: 3
TARGET_VELOCITY: 0.55
TO_GOAL_COST_GAIN: 0.8
TURN_DIRECTION_THRESHOLD: 0.1
USE_FOOTPRINT: false
USE_PATH_COST: false
USE_SCAN_AS_INPUT: false
VELOCITY_SAMPLES: 3
V_PATH_WIDTH: 0.05
YAWRATE_SAMPLES: 20
